version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ../database/db:/var/lib/postgresql/data
      - ../database/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
